# Generated by Django 4.1 on 2024-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='item',
        ),
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.CharField(default='仮名', max_length=100),
        ),
    ]
