# Generated by Django 4.1 on 2024-05-03 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_favorite_item_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sample.item'),
        ),
    ]
