# Generated by Django 4.1 on 2024-05-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_alter_favorite_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchased',
        ),
    ]
