# Generated by Django 4.1 on 2024-05-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_remove_item_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
