# Generated by Django 4.1 on 2024-05-20 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_item_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.category'),
        ),
    ]
