# Generated by Django 4.1 on 2024-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_remove_favorite_item_remove_item_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='sample.item'),
        ),
    ]
