# Generated by Django 4.1 on 2024-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_alter_favorite_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='items',
            field=models.ManyToManyField(blank=True, to='sample.item'),
        ),
    ]
