# Generated by Django 4.1 on 2024-05-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_alter_favorite_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.favorite'),
        ),
    ]
